### ISSUE TITLE
More application examples?

### ISSUE THREAD

**Issue by daweth** [ERC725Alliance/ERC725#68]
Having a hard time justifying the purpose of this contract. Why build another account abstraction on top of an existing accounts structure?

**Comment by YamenMerhi** [comment]
Hey @daweth , I'm not sure which contract you are referring to.

For **ERC725X**, it's just a generic executor that can be implemented in any contract, and then you will have the ability to interact with other addresses on the blockchain with CALL, DELEGATECALL, STATICCALL operations as well as create other contracts with CREATE and CREATE2. This contract could be implemented by DAOs to execute proposals, or by smart contract based account that represents your profile, wallets, etc.

For **ERC725Y**, it's just a generic data key/value store that can store any information as bytes mapped to a bytes32 data key. After deployment you cannot add more variables to smart contracts, that's why a mapping bytes32 has been used to ensure the ability to add huge a number of data keys with a flexible representation of these data keys with bytes32. This contract can be used by any contract wishing to have the ability to add more information to the smart contract so that it can later act on it, such as profiles, digital assets, vaults, etc.

The **ERC725** will form the combination of these 2 contracts.

Happy to discuss further 🚀
